version: "3.9"

services:
  astro-blog:
    container_name: astro-blog
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build && npx serve dist -l 45782"
    ports:
      - "45782:45782"
    restart: unless-stopped
